apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abhi-argocd-nginx
  namespace: argocd
spec:
  project: abhi
  source:
    repoURL: https://github.com/jaindevops/new.git
    targetRevision: argocd
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
