name: Pylint/Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install coverage
    - name: Analysing the code with pylint
      run: |
        pylint --disable missing-docstring python/test/test.py -r n '--msg-template={path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'
     - name: Code Coverage
       run: |
         coverage run python/test/test.py     
         coverage report
