name: "user group sync"
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0 * * *'
  push:
    branches:
      - github_user_sync
    # paths:
    #   - teams/*.csv
jobs:
  user-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: getsentry/action-github-app-token@v2
      name: "Generate test-sync-bot token" 
      id: my-app
      with:
        app_id: "${{ secrets.TEST_SYNC_BOT_APP_ID }}"
        private_key: "${{ secrets.TEST_SYNC_BOT_PRIVATE_KEY }}"
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: jaindevops/terraform
        token: ${{ steps.my-app.outputs.token }}
    - name: "Sync users to groups"
      env:
        GITHUB_TOKEN: "${{ steps.my-app.outputs.token }}"
        src_dir: "${{ github.workspace }}"
      run: |
        teams/sync_users.sh
    # - name: "Sync users to groups"
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.NEW_GITHUB_TOKEN }}"
    #     src_dir: "${{ github.workspace }}"
    #   run: teams/sync_users.sh
