name: "user group sync"
on:
  workflow_dispatch:
  push:
    branches:
      - github_user_sync
jobs:
  user-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: getsentry/action-github-app-token@v2
      name: "Generate sync-bot token" 
      id: psb-token
      with:
        app_id: "${{ secrets.TEST_SYNC_BOT_APP_ID }}"
        private_key: "${{ secrets.TEST_SYNC_BOT_PRIVATE_KEY }}"
    - name: "Sync users to groups"
      env:
        GITHUB_TOKEN: "${{ steps.psb-token.outputs.token }}"
        src_dir: "${{ github.workspace }}"
      run: teams/sync_users.sh